imageName: "nginx"
imageTag: "alpine"
memoryRequest: "128Mi"
cpuRequest: "200m"
memoryLimit: "256Mi"
cpuLimit: "500m"
containerPort: 80
servicePort: 80
hpaMinReplicas: 2
hpaMaxReplicas: 8
hpaTargetCPUUtilizationPercentage: 60
hpaTargetMemoryUtilizationPercentage: 60