imageName: "nginx"
imageTag: "alpine"
memoryRequest: "10Mi"
cpuRequest: "10m"
memoryLimit: "96Mi"
cpuLimit: "50m"
containerPort: 80
servicePort: 80
hpaMinReplicas: 2
hpaMaxReplicas: 8
hpaTargetCPUUtilizationPercentage: 45