apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: my-ws
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx:alpine
        resources:
          requests:
            memory: 64Mi
            cpu: 200m
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: my-ws
spec:
  selector:
    app: myapp
  ports:
  - port: 80
    targetPort: 80
