apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: my-ws
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: {{ .Values.imageName }}:{{ .Values.imageTag }}
        resources:
          requests:
            memory: {{ .Values.memoryRequest }}
            cpu: {{ .Values.cpuRequest }}
          limits:
            memory: {{ .Values.memoryLimit }}
            cpu: {{ .Values.cpuLimit }}
        ports:
        - containerPort: {{ .Values.containerPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: myapp
  namespace: my-ws
spec:
  selector:
    app: myapp
  ports:
  - port: {{ .Values.servicePort }}
    targetPort: {{ .Values.containerPort }}
